site_name: Satoshi Finance Documentation
theme:
  name: material
  favicon: attachment/favicon.ico
  logo: attachment/satofi.png
  language: en
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
- 'index.md'
- 'How to mint btUSD.md'
- 'btUSD stability pool and liquidation.md'
- 'Efficient Redemption.md'
- 'SATO staking.md'
- 'Tokenomics.md'
- 'Testnet.md'
